# Generated by Django 3.0.4 on 2020-03-17 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hallazgo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=100)),
                ('nombre_caso', models.CharField(max_length=100)),
                ('criticidad', models.CharField(choices=[('Crítico', 'Crítico'), ('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo'), ('Informacional', 'Informacional')], default='Crítico', max_length=100)),
                ('estado_actual', models.CharField(choices=[('Vigente', 'Vigente'), ('Caduco', 'Caduco')], default='Vigente', max_length=100)),
                ('fecha_ultima_retroalimentacion', models.DateField()),
                ('mes', models.PositiveIntegerField(blank=True, null=True)),
                ('año', models.PositiveIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
