# Generated by Django 3.0.4 on 2020-03-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threat_hunting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallazgo',
            name='año',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hallazgo',
            name='mes',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo'), ('Abril', 'Abril'), ('Mayo', 'Mayo'), ('Junio', 'Junio'), ('Julio', 'Julio'), ('Agosto', 'Agosto'), ('Septimbre', 'Septimbre'), ('Octubre', 'Octubre'), ('Noviembre', 'Noviembre'), ('Diciembre', 'Diciembre')], max_length=100),
        ),
    ]
