# Generated by Django 3.0.4 on 2020-03-24 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threat_hunting', '0002_auto_20200320_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallazgo',
            name='owner',
        ),
    ]
