# Generated by Django 3.0.4 on 2020-03-16 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos_Del_Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('evento_n1', models.PositiveIntegerField(blank=True, null=True)),
                ('evento_n2', models.PositiveIntegerField(blank=True, null=True)),
                ('evento_n3', models.PositiveIntegerField(blank=True, null=True)),
                ('evento_pro', models.PositiveIntegerField(blank=True, null=True)),
                ('mes', models.PositiveIntegerField(blank=True, null=True)),
                ('año', models.PositiveIntegerField(blank=True, null=True)),
                ('evento_gestionado', models.PositiveIntegerField(blank=True, null=True)),
                ('evento_no_gestionado', models.PositiveIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_del_mes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
