# Generated by Django 3.0.4 on 2020-03-16 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion_de_eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('Integrado', 'Integrado'), ('Modificado', 'Modificado'), ('Eliminado', 'Eliminado')], default='Integrado', max_length=100)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('mes', models.PositiveIntegerField(blank=True, null=True)),
                ('año', models.PositiveIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_source', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
