# Generated by Django 3.0.4 on 2020-03-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_eventos', '0002_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_source',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
