# Generated by Django 3.0.4 on 2020-03-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_eventos', '0004_auto_20200319_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventos_del_mes',
            options={'ordering': ['created'], 'verbose_name': 'Eventos Del Mes', 'verbose_name_plural': 'Eventos Del Mes'},
        ),
    ]
