# Generated by Django 3.0.4 on 2020-03-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_eventos', '0005_auto_20200320_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data_source',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='eventos_del_mes',
            name='owner',
        ),
    ]
