# Generated by Django 3.0.4 on 2020-03-18 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerabilidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fech_fin', models.DateField()),
                ('tipo_escaner', models.CharField(choices=[('Perimetral', 'Perimetral'), ('Interno', 'Interno')], default='Perimetral', max_length=100)),
                ('direcciones_ip_declaradas', models.GenericIPAddressField()),
                ('direcciones_ip_con_respuesta', models.GenericIPAddressField()),
                ('direcciones_ip_sin_respuesta', models.GenericIPAddressField()),
                ('cantidad_nivel_4', models.SmallIntegerField()),
                ('cantidad_nivel_3', models.SmallIntegerField()),
                ('evolucion_fecha_1', models.DateField()),
                ('evolucion_fecha_2', models.DateField()),
                ('evolucion_criticas_1', models.SmallIntegerField()),
                ('evolucion_criticas_2', models.SmallIntegerField()),
                ('evolucion_altas_1', models.SmallIntegerField()),
                ('evolucion_altas_2', models.SmallIntegerField()),
                ('evolucion_medias_1', models.SmallIntegerField()),
                ('evolucion_medias_2', models.SmallIntegerField()),
                ('evolucion_bajas_1', models.SmallIntegerField()),
                ('evolucion_bajas_2', models.SmallIntegerField()),
                ('estado_nuevas', models.SmallIntegerField()),
                ('estado_no_detectadas', models.SmallIntegerField()),
                ('estado_persistentes', models.SmallIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilidad', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
