# Generated by Django 3.0.4 on 2020-03-18 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_vulnerabilidades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vulnerabilidad',
            old_name='fech_fin',
            new_name='fecha_fin',
        ),
    ]
