# Generated by Django 3.0.4 on 2020-03-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_vulnerabilidades', '0002_auto_20200318_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='cantidad_nivel_3',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='cantidad_nivel_4',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='estado_no_detectadas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='estado_nuevas',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='estado_persistentes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='evolucion_altas_1',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='evolucion_altas_2',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='evolucion_bajas_1',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='evolucion_bajas_2',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='evolucion_criticas_1',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='evolucion_criticas_2',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='evolucion_medias_1',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vulnerabilidad',
            name='evolucion_medias_2',
            field=models.PositiveIntegerField(),
        ),
    ]
