# Generated by Django 3.0.4 on 2020-03-17 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tendencia_Amenaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion_1', models.TextField(blank=True, null=True)),
                ('descripcion_2', models.TextField(blank=True, null=True)),
                ('descripcion_3', models.TextField(blank=True, null=True)),
                ('imagen_1', models.ImageField(blank=True, null=True, upload_to='gestion_de_amenazas/tendencia_amenaza/')),
                ('imagen_2', models.ImageField(blank=True, null=True, upload_to='gestion_de_amenazas/tendencia_amenaza/')),
                ('imagen_3', models.ImageField(blank=True, null=True, upload_to='gestion_de_amenazas/tendencia_amenaza/')),
                ('mes', models.PositiveIntegerField(blank=True, null=True)),
                ('año', models.PositiveIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tendencia_Amenaza', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Grafico_Lineas_Tendencia_Amenazas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('escala', models.PositiveIntegerField(blank=True, null=True)),
                ('indicador', models.CharField(blank=True, max_length=100, null=True)),
                ('puntos', models.PositiveIntegerField(blank=True, null=True)),
                ('mes', models.PositiveIntegerField(blank=True, null=True)),
                ('año', models.PositiveIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Grafico_lineas_tendencia_amenazas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Amenazas_Del_Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('Gestionadas', 'Gestionadas'), ('No Gestionadas', 'No Gestionadas')], default='Gestionadas', max_length=100)),
                ('criticidad', models.CharField(choices=[('Crítico', 'Crítico'), ('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo'), ('Informacional', 'Informacional')], default='Crítico', max_length=100)),
                ('tipo', models.CharField(choices=[('Malware', 'Malware'), ('Vulnerabilidad', 'Vulnerabilidad'), ('Parche', 'Parche'), ('APT', 'APT'), ('Phishing', 'Phishing')], default='Malware', max_length=100)),
                ('cantidad', models.PositiveIntegerField(blank=True, null=True)),
                ('mes', models.PositiveIntegerField(blank=True, null=True)),
                ('año', models.PositiveIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenazas_del_mes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Alerta_Amenaza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('Gestionadas', 'Gestionadas'), ('No Gestionadas', 'No Gestionadas')], default='Gestionadas', max_length=100)),
                ('criticidad', models.CharField(choices=[('Crítico', 'Crítico'), ('Alto', 'Alto'), ('Medio', 'Medio'), ('Bajo', 'Bajo'), ('Informacional', 'Informacional')], default='Crítico', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.ImageField(blank=True, null=True, upload_to='gestion_de_amenazas/alerta_amenaza/')),
                ('mes', models.PositiveIntegerField(blank=True, null=True)),
                ('año', models.PositiveIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerta_amenaza', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
