# Generated by Django 3.0.4 on 2020-03-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_amenazas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenazas_del_mes',
            name='mes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
