# Generated by Django 3.0.4 on 2020-03-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_amenazas', '0003_auto_20200319_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta_amenaza',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='media/alerta_amenaza/'),
        ),
    ]
