# Generated by Django 3.0.4 on 2020-03-20 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_de_amenazas', '0005_auto_20200319_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenazas_del_mes',
            options={'ordering': ['created'], 'verbose_name': 'Amenazas Del Mes', 'verbose_name_plural': 'Amenazas Del Mes'},
        ),
        migrations.AlterModelOptions(
            name='grafico_lineas_tendencia_amenazas',
            options={'ordering': ['created'], 'verbose_name': 'Grafico Lineas Tendencia Amenazas', 'verbose_name_plural': 'Grafico Lineas Tendencia Amenazas'},
        ),
    ]
